### ISSUE TITLE
Working with snap4arduino?

### ISSUE THREAD

**Issue by mprogers** [firmata/spark#7]
Forgive the ignorance of this question ... I am using my Photon with [Snap4Arduino](http://snap4arduino.org/index.html) (thanks to your most excellent software), but am wondering if, once this firmware is loaded, it is possible to still take advantage of Photon's capabilities (event publishing, particle function calls, particle variable access, etc.).

**Comment by soundanalogous** [comment]
No, Firmata doesn't expose those capabilities.
